### PR TITLE
Fix: failing tests with datetime

### LINKED ISSUE #22: DomainRow.spec.js test fails
Running `npm run test` we notice that DomainRow.spec.js fails test.
According to @svedova , from now tests will be executed before deployment.

### PR DESCRIPTION
**Pull request by svedova**
`toLocaleDateString` was failing inconsistently because every node environment has its own locale definitions. This PR mocks the `Date` object and returns always `ISO8601` for tests. Some of the files were migrated to typescript as well.

Closes #22

### CODE REVIEW

File: testing/setup.js [hunk 1]
```diff
@@ -4,6 +4,23 @@ import { JSDOM } from "jsdom";
...
+      this.getFullYear() +
+      "-" +
+      ("0" + (this.getMonth() + 1)).slice(-2) +
+      "-" +
+      ("0" + this.getDate()).slice(-2)
+    );
+  }
+}
+
+global.Date = MockDate;
```
Comment (svedova) [inline testing/setup.js:22]: This is the the relevant change.
